version: '2'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}

  tests:
    extends: base
    command: dockerize -wait tcp://kindle_mongo.local:27017 bundle exec "rubocop && thor test:spec"
    environment:
      - MONGO_DB_URL=mongodb://kindle_mongo.local:27017/clippings_test
    links:
      - kindle_mongo:kindle_mongo.local

  kindle_mongo:
    image: mongo:3.2
    command: "--smallfiles"